version: '3'

services:
  devopslabs-ci-build:
    image: labstest.azurecr.io/aspnetcore-build:1.0-2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./TechSummitDemo/TechSummitDemo.csproj && dotnet publish ./TechSummitDemo/TechSummitDemo.csproj -c Release -o ./obj/Docker/publish"

